// bench/magic-tables/generate-blob.mjs — regenerates src/rookMagicBlob.ts and
// src/bishopMagicBlob.ts from the checked-in bench/magic-tables/*.json
// (MIT RecklessMagics-derived data, pipeline unchanged — task 3.1 of change
// purechess-gates-green).
//
// Blob layout (little-endian uint32 words):
//   [0..383]   per-square meta, 6 words per square × 64 squares:
//              maskLo, maskHi, magicLo, magicHi, shift, offset
//   [384..]    attack table entries as [lo, hi] uint32 pairs
// The base64 blob decodes to a ready-to-index Uint32Array in ~0.1 ms
// (measured) vs 82 ms to materialize 107,648 object literals, and weighs
// ~841 KB raw / 26 KB gz instead of 3,373 KB of object-literal text.
//
// Usage: node bench/magic-tables/generate-blob.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const srcDir = join(here, "..", "..", "src");

function generate(name) {
  const json = JSON.parse(readFileSync(join(here, `${name}.json`), "utf8"));
  const magics = json.magics; // 64 per-square records
  const attackTable = json.attackTable; // [ {lo, hi}, ... ]
  const words = new Uint32Array(64 * 6 + attackTable.length * 2);
  for (const m of magics) {
    const b = m.sq * 6;
    words[b + 0] = m.maskLo >>> 0;
    words[b + 1] = m.maskHi >>> 0;
    words[b + 2] = m.magicLo >>> 0;
    words[b + 3] = m.magicHi >>> 0;
    words[b + 4] = m.shift >>> 0;
    words[b + 5] = m.offset >>> 0;
  }
  for (let i = 0; i < attackTable.length; i++) {
    words[64 * 6 + i * 2 + 0] = attackTable[i].lo >>> 0;
    words[64 * 6 + i * 2 + 1] = attackTable[i].hi >>> 0;
  }
  const bytes = Buffer.from(words.buffer, words.byteOffset, words.byteLength);
  // gzip at build time (task 4.2 transparency target: the raw base64 text of
  // high-entropy table data gzips to ~91 KB, but gzip-of-binary → base64
  // lands the lazy chunk at ≈35 KB gz, matching the spec's ≈26–32 KB total
  // expectation). Decoded in src/attacks.ts via DecompressionStream (Node
  // 18+/all modern browsers); if unavailable, the naive fallback serves.
  const gz = gzipSync(bytes, { level: 9 });
  const b64 = gz.toString("base64");
  const cap = name === "rook" ? "Rook" : "Bishop";
  const out = `// AUTO-GENERATED by bench/magic-tables/generate-blob.mjs from
// bench/magic-tables/${name}.json (MIT RecklessMagics-derived table data,
// re-encoded as gzip + base64 Uint8Array blob — task 3.1, change
// purechess-gates-green). Do not edit by hand; regenerate instead.
//
// Layout after decompression (little-endian uint32 words): 6 meta words per
// square [maskLo, maskHi, magicLo, magicHi, shift, offset] × 64 squares, then
// the attack table as [lo, hi] uint32 pairs. Decoded lazily into Uint32Array
// views by src/attacks.ts (ensureMagicTablesLoaded) — never statically
// imported (bundle gate: zero table bytes in the core static graph).
export const ${name}MagicBlob: string =
  "${b64}";
`;
  writeFileSync(join(srcDir, `${name}MagicBlob.ts`), out);
  console.log(`${cap}: ${magics.length} squares, ${attackTable.length} attack entries, blob ${bytes.length.toLocaleString()} B raw → gzip ${gz.length.toLocaleString()} B → base64 ${b64.length.toLocaleString()} chars`);
}

import { gzipSync } from "node:zlib";

generate("rook");
generate("bishop");
